#!/usr/bin/env python3
"""Emit config/markets.yaml entries from bundled census-style city CSV.

Usage:
  python scripts/generate_state_markets.py --state AZ
  python scripts/generate_state_markets.py --all-states --write config/markets_generated.yaml
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CSV = REPO_ROOT / "data" / "us_cities_30k.csv"

TARGET_STATES = ("HI", "OR", "WA", "AZ", "NV", "NM", "CA")
CA_EXCLUDED_COUNTIES = frozenset({"los_angeles_ca", "orange_ca"})

STATE_REGIONS = {
    "HI": "hawaii",
    "OR": "oregon",
    "WA": "washington",
    "AZ": "arizona",
    "NV": "nevada",
    "NM": "new_mexico",
    "CA": "california_expansion",
}


def slugify(text: str) -> str:
    out = []
    for ch in text.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in {" ", "-", "_"}:
            out.append("_")
    slug = "".join(out).strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug


def search_radius_for_population(population: int) -> int:
    if population >= 500_000:
        return 30_000
    if population >= 200_000:
        return 25_000
    if population >= 100_000:
        return 20_000
    return 15_000


def bbox_for_point(lat: float, lon: float, radius_m: int) -> list[float]:
    lat_delta = radius_m / 111_000.0
    lon_delta = radius_m / (111_000.0 * max(math.cos(math.radians(lat)), 0.2))
    return [
        round(lat - lat_delta, 4),
        round(lon - lon_delta, 4),
        round(lat + lat_delta, 4),
        round(lon + lon_delta, 4),
    ]


def load_cities(
    csv_path: Path,
    *,
    states: tuple[str, ...],
    min_population: int,
) -> list[dict[str, str | int | float]]:
    rows: list[dict[str, str | int | float]] = []
    with csv_path.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            state = row["state"].strip().upper()
            if state not in states:
                continue
            county_key = row["county_key"].strip()
            if state == "CA" and county_key in CA_EXCLUDED_COUNTIES:
                continue
            population = int(row["population"])
            if population < min_population:
                continue
            rows.append(
                {
                    "city": row["city"].strip(),
                    "state": state,
                    "county_key": county_key,
                    "latitude": float(row["latitude"]),
                    "longitude": float(row["longitude"]),
                    "population": population,
                }
            )
    return rows


def market_key_for(city: str, state: str) -> str:
    return f"{slugify(city)}_{state.lower()}"


def render_market_entry(row: dict[str, str | int | float]) -> str:
    city = str(row["city"])
    state = str(row["state"])
    key = market_key_for(city, state)
    lat = float(row["latitude"])
    lon = float(row["longitude"])
    population = int(row["population"])
    radius = search_radius_for_population(population)
    region = STATE_REGIONS.get(state, slugify(state))
    county_key = str(row["county_key"])
    bbox = bbox_for_point(lat, lon, radius)
    lines = [
        f"  {key}:",
        f"    city: {city}",
        f"    state: {state}",
        f"    region: {region}",
        f"    county: {county_key}",
        f"    latitude: {lat}",
        f"    longitude: {lon}",
        f"    search_radius_m: {radius}",
        f"    bbox: {bbox}",
    ]
    if population >= 400_000:
        lines.append("    grid_radius_m: 40000")
    return "\n".join(lines)


def render_markets_yaml(rows: list[dict[str, str | int | float]]) -> str:
    seen: set[str] = set()
    entries: list[str] = []
    for row in sorted(rows, key=lambda r: (str(r["state"]), str(r["city"]))):
        key = market_key_for(str(row["city"]), str(row["state"]))
        if key in seen:
            continue
        seen.add(key)
        entries.append(render_market_entry(row))
    header = "# Generated by scripts/generate_state_markets.py — do not hand-edit\nmarkets:"
    return header + "\n" + "\n".join(entries) + "\n"


def market_keys_for_state(rows: list[dict[str, str | int | float]], state: str) -> list[str]:
    keys: list[str] = []
    seen: set[str] = set()
    for row in rows:
        if str(row["state"]) != state:
            continue
        key = market_key_for(str(row["city"]), state)
        if key not in seen:
            seen.add(key)
            keys.append(key)
    return keys


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate markets.yaml entries from census CSV")
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV, help="Input CSV path")
    parser.add_argument(
        "--state",
        action="append",
        help="Two-letter state code (repeatable). Default: all target states",
    )
    parser.add_argument("--min-population", type=int, default=30_000)
    parser.add_argument("--write", type=Path, help="Write YAML fragment to this path")
    parser.add_argument(
        "--list-keys",
        action="store_true",
        help="Print market keys one per line (for campaign.yaml)",
    )
    args = parser.parse_args(argv)

    states = tuple(s.upper() for s in args.state) if args.state else TARGET_STATES
    if not args.csv.exists():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        return 1

    rows = load_cities(args.csv, states=states, min_population=args.min_population)
    if not rows:
        print("No cities matched filters", file=sys.stderr)
        return 1

    if args.list_keys:
        for state in states:
            for key in market_keys_for_state(rows, state):
                print(key)
        return 0

    yaml_text = render_markets_yaml(rows)
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(yaml_text, encoding="utf-8")
        print(f"Wrote {len(rows)} market(s) to {args.write}")
    else:
        sys.stdout.write(yaml_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
