#!/usr/bin/env python3
"""Sync config/decision_roles.yaml → dashboard/lib/generated/decision-roles.ts."""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = ROOT / "config" / "decision_roles.yaml"
OUT_PATH = ROOT / "dashboard" / "lib" / "generated" / "decision-roles.ts"


def main() -> None:
    data = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8")) or {}
    roles = [str(r) for r in (data.get("decision_roles") or [])]
    facilities = [str(p) for p in (data.get("facilities_role_patterns") or [])]
    junk = [str(p) for p in (data.get("junk_role_patterns") or [])]
    if not roles:
        raise SystemExit("decision_roles.yaml missing decision_roles")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = f"""/* Auto-generated by scripts/sync_decision_roles.py — do not edit by hand. */
/* Source: config/decision_roles.yaml */

export const DECISION_ROLES = {json.dumps(roles, indent=2)} as const;

export const FACILITIES_ROLE_PATTERN = {json.dumps("|".join(facilities))};

export const JUNK_ROLE_PATTERN = {json.dumps("|".join(junk))};
"""
    OUT_PATH.write_text(body, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} ({len(roles)} roles)")


if __name__ == "__main__":
    main()
